"""empty message

Revision ID: 10ab33d1590d
Revises: 29f010f7cad4
Create Date: 2021-06-29 17:46:25.092590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ab33d1590d'
down_revision = '29f010f7cad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynamsim', sa.Integer(), nullable=True),
    sa.Column('pasion', sa.Integer(), nullable=True),
    sa.Column('practises_example', sa.Integer(), nullable=True),
    sa.Column('near', sa.Integer(), nullable=True),
    sa.Column('date_teacher', sa.Date(), nullable=False),
    sa.Column('more_info', sa.String(length=500), nullable=True),
    sa.Column('gif', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('img_url', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'school_id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('linkedin', sa.String(length=120), nullable=True),
    sa.Column('type_of_teacher', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    op.drop_table('student')
    op.drop_table('school_user')
    op.drop_table('school')
    op.drop_table('review_teacher')
    # ### end Alembic commands ###
