"""empty message

Revision ID: 44c305def1b9
Revises: dec39b3fbb63
Create Date: 2021-07-01 13:11:47.187498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c305def1b9'
down_revision = 'dec39b3fbb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_student', sa.Boolean(), nullable=False))
    op.drop_column('user', 'student')
    op.drop_column('user', 'password')
    op.drop_column('user', 'teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('teacher', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('student', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_student')
    # ### end Alembic commands ###
