"""empty message

Revision ID: 52bce97b04f0
Revises: 8efb9ecc619a
Create Date: 2021-08-19 15:50:03.602638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bce97b04f0'
down_revision = '8efb9ecc619a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'location')
    # ### end Alembic commands ###
