"""empty message

Revision ID: 864e944da06e
Revises: 0d08b641cf80
Create Date: 2021-07-20 16:05:39.277324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864e944da06e'
down_revision = '0d08b641cf80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
