"""empty message

Revision ID: 90702c0585fa
Revises: 864e944da06e
Create Date: 2021-07-21 16:03:02.320646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90702c0585fa'
down_revision = '864e944da06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_school', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('user_school', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_school', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_school', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_school', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_school', 'id')
    # ### end Alembic commands ###
