"""empty message

Revision ID: dec39b3fbb63
Revises: 10ab33d1590d
Create Date: 2021-06-29 17:47:26.679229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec39b3fbb63'
down_revision = '10ab33d1590d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('promo', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('student', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('teacher', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'teacher')
    op.drop_column('user', 'student')
    op.drop_column('user', 'promo')
    # ### end Alembic commands ###
