"""empty message

Revision ID: f8c7ec13eac4
Revises: a9b9f51edd20
Create Date: 2021-07-22 22:29:57.921783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c7ec13eac4'
down_revision = 'a9b9f51edd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynamsim', sa.Integer(), nullable=True),
    sa.Column('pasion', sa.Integer(), nullable=True),
    sa.Column('practises_example', sa.Integer(), nullable=True),
    sa.Column('near', sa.Integer(), nullable=True),
    sa.Column('date_teacher', sa.Date(), nullable=False),
    sa.Column('more_info', sa.String(length=500), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['user_teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_teacher')
    # ### end Alembic commands ###
